# Generated by Django 3.0.5 on 2020-04-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200409_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagoary',
            new_name='category',
        ),
    ]
